#!/bin/bash

# This Linux/macOS shell script ensures that the source mount points in devcontainer.json exist on the host.

echo "initializeCommand starting..."

echo "Ensuring mount points exist..."
touch ../mounts/~/.bash_history

echo "initializeCommand finished."
